####################
# Original:
#   https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/docker-compose.dev.yml
# 
# Command Note:
#   $ docker compose -f docker-compose.yml build
#   $ docker compose -f docker-compose.yml up
####################

version: '3'

services:
  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
  signalingserver:
    container_name: signalingserver
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - 8080:8080