/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/models/glb/radiation/Bed_rough.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useMatcapTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Bed: THREE.SkinnedMesh;
        Root: THREE.Bone;
    };
    materials: {};
};

import { applyBasePath } from "../../../utils";
const modelURL = applyBasePath(
    `/models/glb/environments/machine/Bed_rough.glb`
);

export function BedRough(props: JSX.IntrinsicElements["group"]) {
    const { nodes, materials } = useGLTF(modelURL) as GLTFResult;

    const [BedMatcap] = useMatcapTexture("28292A_D3DAE5_A3ACB8_818183", 512);

    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Root} />
            <skinnedMesh
                geometry={nodes.Bed.geometry}
                material={nodes.Bed.material}
                skeleton={nodes.Bed.skeleton}
            >
                <meshMatcapMaterial attach="material" matcap={BedMatcap} />
            </skinnedMesh>
        </group>
    );
}

useGLTF.preload(modelURL);
