/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/models/glb/environments/machine/Bed_norig_rough.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useMatcapTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Bednorig: THREE.Mesh;
    };
    materials: {};
};

import { applyBasePath } from "../../../utils";
const modelURL = applyBasePath(
    `/models/glb/environments/machine/Bed_norig_rough.glb`
);

export function BedNorigRough(props: JSX.IntrinsicElements["group"]) {
    const { nodes, materials } = useGLTF(modelURL) as GLTFResult;

    const [BedMatcap] = useMatcapTexture("28292A_D3DAE5_A3ACB8_818183", 512);

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Bednorig.geometry}
                material={nodes.Bednorig.material}
            >
                <meshMatcapMaterial attach="material" matcap={BedMatcap} />
            </mesh>
        </group>
    );
}

useGLTF.preload(modelURL);
