/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 x-ray_machine.glb -o XRay_Machine.tsx -t 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        machine: THREE.Mesh;
    };
    materials: {
        mat1: THREE.MeshStandardMaterial;
    };
};

type ContextType = Record<
    string,
    React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

import { applyBasePath } from "../../../../utils";
const modelURL = applyBasePath(`/models/glb/radiation/x-ray/x-ray_machine.glb`);

export function XRay_Machine(props: JSX.IntrinsicElements["group"]) {
    const { nodes, materials } = useGLTF(modelURL) as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.machine.geometry} material={materials.mat1} />
        </group>
    );
}

useGLTF.preload(modelURL);
