from . import cividis
from . import cubeHelix
from . import githubColor
from . import gray
from . import heat
from . import hot
from . import inferno
from . import jet
from . import magma
from . import parula
from . import plasma
from . import turbo
from . import viridis
