import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import styles from "../styles/Home.module.css";

import { applyBasePath } from "../components/utils";
const logoURL = applyBasePath("/vercel.svg");

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Radiation Protection Education</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Radiation Protection Education</h1>

                <p className={styles.description}>
                    <a href="https://nextjs.org">Next.js</a>,
                    <a href="https://docs.pmnd.rs/react-three-fiber/getting-started/introduction">
                        React Three Fiber
                    </a>
                </p>
                {/* <p>process.env.NODE_ENV {process.env.NODE_ENV}</p> */}

                <h2>Content</h2>
                <div className={styles.grid}>
                    <div className={styles.card}>
                        <Link href={"/volume_visualization/example_stent"}>
                            <h2>Example Stent.nrrd &rarr;</h2>
                            <p>Next.js + react-three/fiber, Texture 3D</p>
                        </Link>
                    </div>

                    <div className={styles.card}>
                        <Link href={"/volume_visualization/dose_visualization"}>
                            <h2>Dose Visualization &rarr;</h2>
                            <p>Next.js + react-three/fiber, Texture 3D</p>
                        </Link>
                    </div>

                    <div className={styles.card}>
                        <Link
                            href={
                                "/volume_visualization/dose_visualization_multi-object"
                            }
                        >
                            <h2>Dose Visualization Multi-Object&rarr;</h2>
                            <p>Next.js + react-three/fiber, Texture 3D</p>
                        </Link>
                    </div>

                    <div className={styles.card}>
                        <Link
                            href={
                                "/volume_visualization/dose_visualization_curtain"
                            }
                        >
                            <h2>
                                Dose Visualization Curtain (&alpha;
                                Version)&rarr;
                            </h2>
                            <p>Next.js + react-three/fiber, Texture 3D</p>
                        </Link>
                    </div>

                    <div className={styles.card}>
                        <Link
                            href={
                                "/volume_visualization/dose_visualization_board_prototype"
                            }
                        >
                            <h2>
                                Dose Visualization Board Prototype (&alpha;
                                Version)&rarr;
                            </h2>
                            <p>Next.js + react-three/fiber, Texture 3D</p>
                        </Link>
                    </div>

                    <div className={styles.card}>
                        <Link href={"/volume_visualization/stent_and_dose"}>
                            <h2>Stent and Dose</h2>
                            <p>Next.js + react-three/fiber, Texture 3D</p>
                        </Link>
                    </div>

                    {/* <div className={styles.card}>
                        <Link
                            href={"/volume_visualization/dose_visualization_VR"}
                        >
                            <h2>
                                Dose Visualization (Ver. VR, &alpha;
                                Version)&rarr;
                            </h2>
                            <p>
                                Next.js + react-three/fiber + react-three/xr,
                                Texture 3D
                            </p>
                        </Link>
                    </div> */}

                    <div className={styles.card}>
                        <Link href={"/multiplay/game_sample"}>
                            <h2>Game Sample &rarr;</h2>
                            <p>Next.js + react-three/fiber</p>
                        </Link>
                    </div>

                    {/* <div className={styles.card}>
                        <Link href={"/multiplay/the_picture_gallery"}>
                            <h2>The Picture Gallery (Not Support)</h2>
                            <p>Next.js + react-three/fiber</p>
                        </Link>
                    </div> */}

                    <div className={styles.card}>
                        <Link href={"/multiplay/stent_game"}>
                            <h2>Stent + Game &rarr;</h2>
                            <p>Next.js + react-three/fiber</p>
                        </Link>
                    </div>

                    <div className={styles.card}>
                        <Link href={"/multiplay/xray_game"}>
                            <h2>XRay + Game &rarr;</h2>
                            <p>Next.js + react-three/fiber</p>
                        </Link>
                    </div>

                    <div className={styles.card}>
                        <Link href={"/rough_scenes/c-arm_scene_rough"}>
                            <h2>C-Arm Scene &rarr;</h2>
                            <p>Next.js + react-three/fiber</p>
                        </Link>
                    </div>
                    <div className={styles.card}>
                        <Link href={"/rough_scenes/XRay_position_scale_rough"}>
                            <h2>XRay Scale Scene &rarr;</h2>
                            <p>Next.js + react-three/fiber</p>
                        </Link>
                    </div>
                </div>

                <h2>References</h2>
                <div className={styles.grid}>
                    <a
                        href="https://threejs.org/examples/?q=texture3d#webgl2_materials_texture3d"
                        className={styles.card}
                    >
                        <h2>Textrue3D example &rarr;</h2>
                        <p>Three.js examples</p>
                    </a>

                    <a
                        href="https://threejs.org/examples/?q=nrrd#webgl_loader_nrrd"
                        className={styles.card}
                    >
                        <h2>NRRDLoader example &rarr;</h2>
                        <p>Three.js examples</p>
                    </a>

                    <a
                        href="https://github.com/cornerstonejs/cornerstoneTools/issues/335#issuecomment-376008409"
                        className={styles.card}
                    >
                        <h2>NRRD Production example &rarr;</h2>
                        <p>Three.js + NRRD Production</p>
                    </a>

                    <a
                        href="https://contsrv.icer.kyushu-u.ac.jp/Medu/XraySim/"
                        className={styles.card}
                    >
                        <h2>Radiation visualization 1 &rarr;</h2>
                        <p>A-Frame</p>
                    </a>

                    <a
                        href="https://contsrv.icer.kyushu-u.ac.jp/Medu/XraySim2/"
                        className={styles.card}
                    >
                        <h2>Radiation visualization 2 &rarr;</h2>
                        <p>A-Frame</p>
                    </a>

                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>
                            Find in-depth information about Next.js features and
                            API.
                        </p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>
                            Learn about Next.js in an interactive course with
                            quizzes!
                        </p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/canary/examples"
                        className={styles.card}
                    >
                        <h2>Examples &rarr;</h2>
                        <p>
                            Discover and deploy boilerplate example Next.js
                            projects.
                        </p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>
                            Instantly deploy your Next.js site to a public URL
                            with Vercel.
                        </p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://github.com/Ireansan"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by Ireansan
                </a>
            </footer>
        </div>
    );
};

export default Home;
