import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import styles from "../styles/Home.module.css";

import { applyBasePath } from "../utils";
const logoURL = applyBasePath("/vercel.svg");

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Radiation Protection Education</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Radiation Protection Education</h1>

                <p className={styles.description}>
                    <a href="https://nextjs.org">Next.js</a>,
                    <a href="https://docs.pmnd.rs/react-three-fiber/getting-started/introduction">
                        React Three Fiber
                    </a>
                </p>
                {/* <p>process.env.NODE_ENV {process.env.NODE_ENV}</p> */}

                <h2>Content</h2>
                <h3>Visualization</h3>
                <div className={styles.grid}>
                    <div className={styles.card}>
                        <Link href={"/visualization/X-Ray"}>
                            <h2>X-Ray &rarr;</h2>
                            <p>Next.js + react-three/fiber, Texture 3D</p>
                        </Link>
                    </div>

                    <div className={styles.card}>
                        <Link href={"/visualization/C-Arm"}>
                            <h2>C-Arm (Type 1) &rarr;</h2>
                            <p>Next.js + react-three/fiber, Texture 3D</p>
                        </Link>
                    </div>

                    <div className={styles.card}>
                        <Link href={"/visualization/C-Arm_roll180_pitch360"}>
                            <h2>C-Arm (Type 2) &rarr;</h2>
                            <p>Next.js + react-three/fiber, Texture 3D</p>
                        </Link>
                    </div>
                </div>

                <h3>Visualization Extra</h3>
                <div className={styles.grid}>
                    <div className={styles.card}>
                        <Link href={"/visualization_extra/X-Ray_extra"}>
                            <h2>X-Ray &rarr;</h2>
                            <p>Next.js + react-three/fiber, Texture 3D</p>
                        </Link>
                    </div>

                    <div className={styles.card}>
                        <Link href={"/visualization_extra/C-Arm_extra"}>
                            <h2>C-Arm (Type 1) &rarr;</h2>
                            <p>Next.js + react-three/fiber, Texture 3D</p>
                        </Link>
                    </div>

                    <div className={styles.card}>
                        <Link
                            href={
                                "/visualization_extra/C-Arm_roll180_pitch360_extra"
                            }
                        >
                            <h2>C-Arm (Type 2) &rarr;</h2>
                            <p>Next.js + react-three/fiber, Texture 3D</p>
                        </Link>
                    </div>
                </div>

                <h3>Game</h3>
                <div className={styles.grid}>
                    <div className={styles.card}>
                        <Link href={"/game/room1"}>
                            <h2>Room 1 &rarr;</h2>
                            <p>Next.js + react-three/fiber</p>
                        </Link>
                    </div>

                    <div className={styles.card}>
                        <Link href={"/game/room2"}>
                            <h2>Room 2 &rarr;</h2>
                            <p>Next.js + react-three/fiber</p>
                        </Link>
                    </div>

                    <div className={styles.card}>
                        <Link href={"/game/SampleScene"}>
                            <h2>Sample Scene &rarr;</h2>
                            <p>Next.js + react-three/fiber</p>
                        </Link>
                    </div>

                    <div className={styles.card}>
                        <Link href={"/game/Stent_Game"}>
                            <h2>Stent + Game &rarr;</h2>
                            <p>Next.js + react-three/fiber</p>
                        </Link>
                    </div>

                    <div className={styles.card}>
                        <Link href={"/game/XRay_room_Game"}>
                            <h2>XRay + Game &rarr;</h2>
                            <p>Next.js + react-three/fiber</p>
                        </Link>
                    </div>
                </div>

                <h3>Prototype</h3>
                <div className={styles.grid}>
                    <div className={styles.card}>
                        <Link href={"/prototype/c-arm_scene_rough"}>
                            <h2>C-Arm Scene &rarr;</h2>
                            <p>Next.js + react-three/fiber</p>
                        </Link>
                    </div>
                    <div className={styles.card}>
                        <Link href={"/prototype/XRay_position_scale_rough"}>
                            <h2>XRay Position & Scale &rarr;</h2>
                            <p>Next.js + react-three/fiber</p>
                        </Link>
                    </div>
                    <div className={styles.card}>
                        <Link href={"/prototype/XRay_room_Dosimeter_Prototype"}>
                            <h2>XRay Dosimeter &rarr;</h2>
                            <p>Next.js + react-three/fiber</p>
                        </Link>
                    </div>
                    <div className={styles.card}>
                        <Link href={"/prototype/YBot_IK_Prototype"}>
                            <h2>Y-Bot IK &rarr;</h2>
                            <p>Next.js + react-three/fiber</p>
                        </Link>
                    </div>
                    <div className={styles.card}>
                        <Link href={"/prototype/XRay_room_switch_data"}>
                            <h2>XRay (no)curtain &rarr;</h2>
                            <p>Next.js + react-three/fiber</p>
                        </Link>
                    </div>
                </div>

                <h2>References</h2>
                <div className={styles.grid}>
                    <a
                        href="https://threejs.org/examples/?q=texture3d#webgl2_materials_texture3d"
                        className={styles.card}
                    >
                        <h2>Textrue3D example &rarr;</h2>
                        <p>Three.js examples</p>
                    </a>

                    <a
                        href="https://threejs.org/examples/?q=nrrd#webgl_loader_nrrd"
                        className={styles.card}
                    >
                        <h2>NRRDLoader example &rarr;</h2>
                        <p>Three.js examples</p>
                    </a>

                    <a
                        href="https://github.com/cornerstonejs/cornerstoneTools/issues/335#issuecomment-376008409"
                        className={styles.card}
                    >
                        <h2>NRRD Production example &rarr;</h2>
                        <p>Three.js + NRRD Production</p>
                    </a>

                    <a
                        href="https://contsrv.icer.kyushu-u.ac.jp/Medu/XraySim/"
                        className={styles.card}
                    >
                        <h2>Radiation visualization 1 &rarr;</h2>
                        <p>A-Frame</p>
                    </a>

                    <a
                        href="https://contsrv.icer.kyushu-u.ac.jp/Medu/XraySim2/"
                        className={styles.card}
                    >
                        <h2>Radiation visualization 2 &rarr;</h2>
                        <p>A-Frame</p>
                    </a>

                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>
                            Find in-depth information about Next.js features and
                            API.
                        </p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>
                            Learn about Next.js in an interactive course with
                            quizzes!
                        </p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/canary/examples"
                        className={styles.card}
                    >
                        <h2>Examples &rarr;</h2>
                        <p>
                            Discover and deploy boilerplate example Next.js
                            projects.
                        </p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>
                            Instantly deploy your Next.js site to a public URL
                            with Vercel.
                        </p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://github.com/Ireansan"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by Ireansan
                </a>
            </footer>
        </div>
    );
};

export default Home;
