/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef, useMemo } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { GLTF, CCDIKSolver, CCDIKHelper, IKS } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        bodyankle: THREE.SkinnedMesh;
        bodyarm: THREE.SkinnedMesh;
        bodyear: THREE.SkinnedMesh;
        bodyhand: THREE.SkinnedMesh;
        bodyhead: THREE.SkinnedMesh;
        equipmentapron: THREE.SkinnedMesh;
        equipmentglove: THREE.SkinnedMesh;
        equipmentgoggle: THREE.SkinnedMesh;
        equipmentneck_guard: THREE.SkinnedMesh;
        wearlower: THREE.SkinnedMesh;
        wearshoes: THREE.SkinnedMesh;
        wearupper: THREE.SkinnedMesh;
        mixamorigHips: THREE.Bone;
    };
    materials: {
        Body: THREE.MeshPhysicalMaterial;
        Equipment: THREE.MeshPhysicalMaterial;
        Wear: THREE.MeshPhysicalMaterial;
    };
};

import { useStore } from "../../store";
import { applyBasePath } from "../../../utils";
const modelURL = applyBasePath(`/models/glb/Self-Made_Player.glb`);

type SelfMadePlayerProps = {
    shoulderUp?: boolean;
    rollUp?: boolean;
} & JSX.IntrinsicElements["group"];
export function SelfMadePlayer({
    shoulderUp = false,
    rollUp = false,
    ...props
}: SelfMadePlayerProps) {
    const [debug, playerState] = useStore((state) => [
        state.debug,
        state.sceneStates.playerState,
    ]);
    const { equipments } = playerState;

    const group = useRef<THREE.Group>(null!);

    const { nodes, materials } = useGLTF(modelURL) as GLTFResult;

    const [ccdIkSolver, ccdIkHelper] = useMemo(() => {
        const iks = [
            {
                target: 35, // "mixamorigLeftHandIK"
                effector: 13, // "mixamorigLeftHand"
                links: [
                    {
                        index: 12, // "mixamorigLeftForeArm"
                        rotationMin: new THREE.Vector3(0.0, 0.0, 0.0),
                        rotationMax: new THREE.Vector3(0.1, 0.1, 1.7),
                    },
                    {
                        index: 11, // "mixamorigLeftArm"
                        rotationMin: new THREE.Vector3(
                            shoulderUp ? 0.0 : 1.1,
                            rollUp ? -1.5 : -0.1,
                            0.0
                        ),
                        rotationMax: new THREE.Vector3(1.5, 0.1, 1.7),
                    },
                ],
            },
            {
                target: 61, // "mixamorigRightHandIK"
                effector: 39, // "mixamorigRightHand"
                links: [
                    {
                        index: 38, // "mixamorigRightForeArm"
                        rotationMin: new THREE.Vector3(0.0, 0.0, -1.7),
                        rotationMax: new THREE.Vector3(0.1, 0.1, 0.0),
                    },
                    {
                        index: 37, // "mixamorigRightArm"
                        rotationMin: new THREE.Vector3(
                            shoulderUp ? 0 : 1.1,
                            -0.1,
                            -1.7
                        ),
                        rotationMax: new THREE.Vector3(
                            1.5,
                            rollUp ? 1.5 : 0.1,
                            0.0
                        ),
                    },
                ],
            },
        ] as unknown as IKS[];

        return [
            new CCDIKSolver(nodes.bodyarm, iks),
            // @ts-ignore
            new CCDIKHelper(nodes.bodyarm, iks, 0.025),
        ];
    }, [shoulderUp]);

    React.useEffect(() => {
        console.log(group.current);
    }, [group]);

    useFrame(() => {
        ccdIkSolver.update();
    });

    return (
        <group
            ref={group}
            {...props}
            dispose={null}
        >
            {debug ? <primitive object={ccdIkHelper} /> : null}
            <group
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
            >
                <skinnedMesh
                    geometry={nodes.bodyankle.geometry}
                    material={materials.Body}
                    skeleton={nodes.bodyankle.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.bodyarm.geometry}
                    material={materials.Body}
                    skeleton={nodes.bodyarm.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.bodyear.geometry}
                    material={materials.Body}
                    skeleton={nodes.bodyear.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.bodyhand.geometry}
                    material={materials.Body}
                    skeleton={nodes.bodyhand.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.bodyhead.geometry}
                    material={materials.Body}
                    skeleton={nodes.bodyhead.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.equipmentapron.geometry}
                    material={materials.Equipment}
                    skeleton={nodes.equipmentapron.skeleton}
                    visible={equipments.apron}
                />
                <skinnedMesh
                    geometry={nodes.equipmentglove.geometry}
                    material={materials.Equipment}
                    skeleton={nodes.equipmentglove.skeleton}
                    visible={equipments.glove}
                />
                <skinnedMesh
                    geometry={nodes.equipmentgoggle.geometry}
                    material={materials.Equipment}
                    skeleton={nodes.equipmentgoggle.skeleton}
                    visible={equipments.goggle}
                />
                <skinnedMesh
                    geometry={nodes.equipmentneck_guard.geometry}
                    material={materials.Equipment}
                    skeleton={nodes.equipmentneck_guard.skeleton}
                    visible={equipments.neck}
                />
                <skinnedMesh
                    geometry={nodes.wearlower.geometry}
                    material={materials.Wear}
                    skeleton={nodes.wearlower.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.wearshoes.geometry}
                    material={materials.Wear}
                    skeleton={nodes.wearshoes.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.wearupper.geometry}
                    material={materials.Wear}
                    skeleton={nodes.wearupper.skeleton}
                />
                <primitive object={nodes.mixamorigHips} />
            </group>
        </group>
    );
}

useGLTF.preload(modelURL);

/*
# Bone Structure

```
0   mixamorigHips
1       L mixamorigSpine
2       |   L mixamorigSpine1
3       |       L mixamorigSpine2
4       |       |   L mixamorigNeck
5       |       |   |   L mixamorigHead
6       |       |   |   |   L mixamorigHeadTop_End
7       |       |   |   |   L mixamorigLeftEyeDosimeter
8       |       |   |   |   L mixamorigRightEyeDosimeter
9       |       |   |   L mixamorigNeckDosimeter
10      |       |   L mixamorigLeftShoulder
1       |       |   |   L mixamorigLeftArm
2       |       |   |   |   L mixamorigLeftForeArm
3       |       |   |   |       L mixamorigLeftHand
4       |       |   |   |       |   L mixamorigLeftHandThumb1
5       |       |   |   |       |   |   L mixamorigLeftHandThumb2
6       |       |   |   |       |   |       L mixamorigLeftHandThumb3
7       |       |   |   |       |   |           L mixamorigLeftHandThumb4
8       |       |   |   |       |   L mixamorigLeftHandIndex1
9       |       |   |   |       |   |   L mixamorigLeftHandIndex2
20      |       |   |   |       |   |       L mixamorigLeftHandIndex3
1       |       |   |   |       |   |           L mixamorigLeftHandIndex4
2       |       |   |   |       |   L mixamorigLeftHandMiddle1
3       |       |   |   |       |   |   L mixamorigLeftHandMiddle2
4       |       |   |   |       |   |       L mixamorigLeftHandMiddle3
5       |       |   |   |       |   |           L mixamorigLeftHandMiddle4
6       |       |   |   |       |   L mixamorigLeftHandRing1
7       |       |   |   |       |   |   L mixamorigLeftHandRing2
8       |       |   |   |       |   |       L mixamorigLeftHandRing3
9       |       |   |   |       |   |           L mixamorigLeftHandRing4
30      |       |   |   |       |   L mixamorigLeftHandPinky1
1       |       |   |   |       |       L mixamorigLeftHandPinky2
2       |       |   |   |       |           L mixamorigLeftHandPinky3
3       |       |   |   |       |               L mixamorigLeftHandPinky4
4       |       |   |   |       L mixamorigLeftHandDosimeter
5       |       |   |   L mixamorigLeftHandIK
6       |       |   L mixamorigRightShoulder
7       |       |       L mixamorigRightArm
8       |       |       |   L mixamorigRightForeArm
9       |       |       |       L mixamorigRightHand
40      |       |       |       |   L mixamorigRightHandThumb1
1       |       |       |       |   |   L mixamorigRightHandThumb2
2       |       |       |       |   |       L mixamorigRightHandThumb3
3       |       |       |       |   |           L mixamorigRightHandThumb4
4       |       |       |       |   L mixamorigRightHandIndex1
5       |       |       |       |   |   L mixamorigRightHandIndex2
6       |       |       |       |   |       L mixamorigRightHandIndex3
7       |       |       |       |   |           L mixamorigRightHandIndex4
8       |       |       |       |   L mixamorigRightHandMiddle1
9       |       |       |       |   |   L mixamorigRightHandMiddle2
50      |       |       |       |   |       L mixamorigRightHandMiddle3
1       |       |       |       |   |           L mixamorigRightHandMiddle4
2       |       |       |       |   L mixamorigRightHandRing1
3       |       |       |       |   |   L mixamorigRightHandRing2
4       |       |       |       |   |       L mixamorigRightHandRing3
5       |       |       |       |   |           L mixamorigRightHandRing4
6       |       |       |       |   L mixamorigRightHandPinky1
7       |       |       |       |       L mixamorigRightHandPinky2
8       |       |       |       |           L mixamorigRightHandPinky3
9       |       |       |       |               L mixamorigRightHandPinky4
60      |       |       |       L mixamorigRightHandDosimeter
1       |       |       L mixamorigRightHandIK
2       |       L mixamorigSpine1Dosimeter
3       L mixamorigLeftUpLeg
4       |   L mixamorigLeftLeg
5       |       L mixamorigLeftFoot
6       |           L mixamorigLeftToeBase
7       |               L mixamorigLeftToe_End
8       L mixamorigRightUpLeg
9       |   L mixamorigRightLeg
70      |       L mixamorigRightFoot
1       |           L mixamorigRightToeBase
2       |               L mixamorigRightToe_End
3       L mixamorigHipsDosimeter
```

*/
